apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:masters
      rolearn: arn:aws:iam::595455728308:role/UdacityFlaskDeployCBKubectlRole
      username: build    
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::595455728308:role/eksctl-capstone-jwt-api-nodegroup--NodeInstanceRole-Ss2HHfB7iRgJ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-31T12:43:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1290"
  uid: cfc61693-c7f2-477f-bd30-6c360a568265
